import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration513251747154114227 implements MigrationInterface {
    name = 'Migration513251747154114227'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "article" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" character varying NOT NULL, "short_description" character varying(1000) NOT NULL, "category" character varying NOT NULL, "keywords" text NOT NULL, "author_details" text, "article_file_path" character varying, "article_file_language" character varying, "date_of_article_writing" date, "article_scope" text, "content_type" character varying, "approved_by" integer, "approved_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "magazine" character varying, "magazine_series" character varying, "article_type" character varying, "article_title" character varying, "educational_degree" character varying, "created_by_user_id" uuid, CONSTRAINT "PK_40808690eb7b915046558c0f81b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "article_application" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" character varying NOT NULL, "short_description" character varying(1000) NOT NULL, "category" character varying NOT NULL, "keywords" text NOT NULL, "author_details" text, "article_file_path" character varying, "article_file_language" character varying, "date_of_article_writing" date, "article_scope" text, "content_type" character varying, "approved_by" integer, "approved_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "magazine" character varying, "magazine_series" character varying, "article_type" character varying, "article_title" character varying, "educational_degree" character varying, CONSTRAINT "PK_a2fd6e14deda5213ecbedd58dae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "article_authors" ("article_id" integer NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_9875ebd4bbb0a7bdc21754b7865" PRIMARY KEY ("article_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a045495388d3a462887cc91cfc" ON "article_authors" ("article_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0726609aa7b8a9cd7d53e131d9" ON "article_authors" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "article_application_users" ("application_id" integer NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_29db68cf310a33a85ba4ced7e48" PRIMARY KEY ("application_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3485e43cc10c0c9a2d354ad2cb" ON "article_application_users" ("application_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e6f1ee161e1af7130e297e9d3" ON "article_application_users" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "article" ADD CONSTRAINT "FK_b2643fbc5bc585d91f9d4c360f1" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_authors" ADD CONSTRAINT "FK_a045495388d3a462887cc91cfca" FOREIGN KEY ("article_id") REFERENCES "article"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "article_authors" ADD CONSTRAINT "FK_0726609aa7b8a9cd7d53e131d9b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "article_application_users" ADD CONSTRAINT "FK_3485e43cc10c0c9a2d354ad2cb2" FOREIGN KEY ("application_id") REFERENCES "article_application"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "article_application_users" ADD CONSTRAINT "FK_6e6f1ee161e1af7130e297e9d30" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "article_application_users" DROP CONSTRAINT "FK_6e6f1ee161e1af7130e297e9d30"`);
        await queryRunner.query(`ALTER TABLE "article_application_users" DROP CONSTRAINT "FK_3485e43cc10c0c9a2d354ad2cb2"`);
        await queryRunner.query(`ALTER TABLE "article_authors" DROP CONSTRAINT "FK_0726609aa7b8a9cd7d53e131d9b"`);
        await queryRunner.query(`ALTER TABLE "article_authors" DROP CONSTRAINT "FK_a045495388d3a462887cc91cfca"`);
        await queryRunner.query(`ALTER TABLE "article" DROP CONSTRAINT "FK_b2643fbc5bc585d91f9d4c360f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e6f1ee161e1af7130e297e9d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3485e43cc10c0c9a2d354ad2cb"`);
        await queryRunner.query(`DROP TABLE "article_application_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0726609aa7b8a9cd7d53e131d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a045495388d3a462887cc91cfc"`);
        await queryRunner.query(`DROP TABLE "article_authors"`);
        await queryRunner.query(`DROP TABLE "article_application"`);
        await queryRunner.query(`DROP TABLE "article"`);
    }

}
