import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration61251748761808179 implements MigrationInterface {
    name = 'Migration61251748761808179'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "article_file" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "original_name" character varying NOT NULL, "path" character varying NOT NULL, "mimetype" character varying NOT NULL, "file_type" character varying, "size" integer NOT NULL, "articleApplicationId" integer, CONSTRAINT "PK_28996ef82f797887237726b3e26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "article_application" DROP COLUMN "article_file_path"`);
        await queryRunner.query(`ALTER TABLE "article_application" DROP COLUMN "article_title"`);
        await queryRunner.query(`ALTER TABLE "article_application" ADD "terms_accepted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "article_application" ADD "publication_details" text`);
        await queryRunner.query(`ALTER TABLE "article_application" DROP COLUMN "author_details"`);
        await queryRunner.query(`ALTER TABLE "article_application" ADD "author_details" jsonb`);
        await queryRunner.query(`ALTER TABLE "article_file" ADD CONSTRAINT "FK_29dcab5b7b4baa8050fd60a25c0" FOREIGN KEY ("articleApplicationId") REFERENCES "article_application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "article_file" DROP CONSTRAINT "FK_29dcab5b7b4baa8050fd60a25c0"`);
        await queryRunner.query(`ALTER TABLE "article_application" DROP COLUMN "author_details"`);
        await queryRunner.query(`ALTER TABLE "article_application" ADD "author_details" text`);
        await queryRunner.query(`ALTER TABLE "article_application" DROP COLUMN "publication_details"`);
        await queryRunner.query(`ALTER TABLE "article_application" DROP COLUMN "terms_accepted"`);
        await queryRunner.query(`ALTER TABLE "article_application" ADD "article_title" character varying`);
        await queryRunner.query(`ALTER TABLE "article_application" ADD "article_file_path" character varying`);
        await queryRunner.query(`DROP TABLE "article_file"`);
    }

}
